### PR TITLE
Add Examples folder and first example on using Datapub

### PR DESCRIPTION
**Pull request by risenW**
Task:
- [x] Add example to use two or more basic component 
- [x] Add example to use TableSchema component

### CODE REVIEW

**Comment by kmanaseryan** [comment]
@risenW no need to have a real working app in the project. That's a huge work. Just use only markdowns to describe how to use it, no need any `js` or other files. Just some good examples how to use the lib. You can copy paste a peice of code from any **datahub-xxx** project in your `.md` files and describe the usage.

**Comment by risenW** [comment]
> @risenW no need to have a real working app in the project. That's a huge work. Just use only markdowns to describe how to use it, no need any `js` or other files. Just some good examples how to use the lib. You can copy paste a peice of code from any **datahub-xxx** project in your `.md` files and describe the usage.

Okay, I can get rid of the code folder and just use Markdown then. What do you think of the content structure for the [first example](https://github.com/datopian/datapub/blob/c69a85bdba6c61c210e10e5b21cc52392a7d3749/examples/reusable_datapub_basic.md) though?

**Comment by rufuspollock** [comment]
@risenW if you do have the example then you can commit it ...

**Comment by kmanaseryan** [comment]
@rufuspollock I'm little confused with the examples, maybe will better if you review it

**Comment by rufuspollock** [comment]
@risenW looks good though easier to fully review when merged. minor early review comments:

* subfolders don't generally require a .gitignore
* README are named `README.md` by default

**Comment by risenW** [comment]
> @risenW looks good though easier to fully review when merged. minor early review comments:
> 
> * subfolders don't generally require a .gitignore
> * README are named `README.md` by default

Okay, on it now

**Pull request merged**
